version: '3'

services:
  lek-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lek
    volumes:
      - ./db:/var/lib/postgresql/data

  lek:
    build:
      context: .
      dockerfile: ./Letemknow/Server/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - lek-db