version: '3'

services:
  lek:
    build:
      context: .
      dockerfile: ./Letemknow/Server/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./db:/app/db

  lek-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lek
    volumes:
      - ./postgres:/var/lib/postgresql/data
    